export enum textVariants {
  TITLE_BOLD = 'TITLE_BOLD', //24PX
  TITLE_SEMIBOLD = 'TITLE_SEMIBOLD',
  TITLE_REGULAR = 'TITLE_REGULAR',
  TITLE_LIGHT = 'TITLE_LIGHT',
  SUBTITLE_BOLD = 'SUBTITLE_BOLD', //20PX
  SUBTITLE_SEMIBOLD = 'SUBTITLE_SEMIBOLD',
  SUBTITLE_REGULAR = 'SUBTITLE_REGULAR',
  SUBTITLE_LIGHT = 'SUBTITLE_LIGHT',
  BUTTON_BOLD = 'BUTTON_BOLD', //18PX
  BUTTON_SEMIBOLD = 'BUTTON_SEMIBOLD',
  BUTTON_REGULAR = 'BUTTON_REGULAR',
  BUTTON_LIGHT = 'BUTTON_LIGHT',
  PARAGRAPH_BOLD = 'PARAGRAPH_BOLD', //14PX
  PARAGRAPH_SEMIBOLD = 'PARAGRAPH_SEMIBOLD',
  PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
  PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT',
  PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL_BOLD', //10PX
  PARAGRAPH_SMALL_SEMIBOLD = 'PARAGRAPH_SMALL_SEMIBOLD',
  PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR',
  PARAGRAPH_SMALL_LIGHT = 'PARAGRAPH_SMALL_LIGHT',
}
